version: '3'

services:
  motion_detector:
    # My local image name
    image: motion_recorder # build: .
    volumes:
      - ./src:/usr/src/project
      - ${HostVideoDir}:/usr/src/project/media
      - ${RenderDir}:/usr/src/project/render
    environment:
      - VideoNames=${VideoNames}
      - AreaInterest=${AreaInterest}
